# Parameter store parameters and values
# name
#   - description
#   - value
#   - type - accepts String, StringList, SecureString

test1:
  - "Description 1"
  - stringValue
  - String
test2:
  - "Description 2"
  - secureValue
  - SecureString
#test3:
#  - "Description 3"
#  - 'test3value, test3value2, test3value3'
#  - SecureList'
